export * from './constants.js'
export type { IPacket } from './packet.js'
export type { IHeader } from './header.js'
export type { IFlags } from './flags.js'
export type { IQuestion } from './question.js'
export type { IResourceRecord } from './resource-record.js'
